# FILEPATH: /Users/sandeeppvn/GitHub/AIJobApply/pyproject.toml

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AIJobApply"
version = "1.0.2"
description = "Package to apply for jobs automatically and send emails"
authors = [{name = "Sandeeppvn", email = "sandeeppvn@gmail.com"}]
readme = "README.md"
dependencies = [
    "ConfigParser==6.0.0",
    "openai==0.28.1",
    "PyPDF2==3.0.1",
    "pytest==7.4.3",
    "python-dotenv==1.0.0",
    "tqdm==4.65.0",
    "requests==2.28.2",
    "gspread==5.12.0",
    "pandas==2.1.2",
    "selenium==4.16.0",
    "pyautogui==0.9.54",
]

[project.urls]
homepage =  "https://github.com/sandeeppvn/AIJobApply"

[project.scripts]
aijobapply = "src.main:aijobapply_cli"



